
@api = http://localhost:5000/students


### get product
{{api}}

### get planificacion
GET http://localhost:5000/renderizarPlanificacion


POST http://localhost:5000/enviarPlanificacion
Content-Type: application/json
{
    "FechaInicio": "2023-01-17",
    "FechaFinal": "2023-05-12",
    "PeriodoAcademico": "1PAC"
}
### add nueva planificacion
POST http://localhost:5000/enviarPlanificacion
Content-Type: application/json

{
    "FechaInicio": "2023-05-22",
    "FechaFinal": "2023-09-01",
    "PeriodoAcademico": "2PAC"
}
POST http://localhost:5000/enviarMatricula
Content-Type: application/json

{
    "FechaInicio": "2023-09-09",
    "FechaFinal": "2023-09-12",
    "HoraInicio": "09:00:00",
    "HoraFinal": "11:59:59",
    "PeriodoAcademico": "3PAC"
}

GET http://localhost:5000/enviarPlanificacionIPAC


### ver clases que esta cursando un estudiante
post http://localhost:5000/enviarClasesQueEstaCursando
Content-Type: application/json

{
    "NumCuenta": "20182001940",
    "Periodo": "2PAC",
    "año": 2023
}

### ver clases que esta cursando un estudiante
post http://localhost:5000/enviarSolicitudesRealizadas
Content-Type: application/json

{
    "NumCuenta": "20182001940",
    "Periodo": "2PAC",
    "año": 2023
}


### ver clases que esta cursando un estudiante
post http://localhost:5000/enviarInformacionEstudiante
Content-Type: application/json

{
    "NumCuenta": "20182001940"
}


### get planificacion
GET http://localhost:5000/enviarSolicitudesRealizadasCoordinador

### ver clases que esta cursando un estudiante
post http://localhost:5000/download-pdf
Content-Type: application/json

{
    "NumCuenta": "20182001940"
}
